#
# Continuous Integration (CI) Pipeline
#

trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
    - feature/*
pr:
- master
- release/*
- feature/*

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build_solution
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: clog.sln\clog.sln
